### ISSUE TITLE
Adding product directly from shop page - no dependency message is seen.

### ISSUE THREAD

**Issue by paaljoachim** [somewherewarm/woocommerce-product-dependencies#30] opened 2018-02-16 19:14 UTC
Hey

Adding the bottom product "Et annet produkt" directly from the shop page to the cart it looks like it is not added to the cart. https://4qm5wltazp2zx547.prev.site/

It looks like no dependency message shows up directly on the shop page.
I click the cart page and notice the dependency message there.

**Comment by franticpsyx** [comment] 2018-02-19 09:17
I assume this is a duplicate of #29 ?

**Closed by franticpsyx** 2018-02-19 09:17 UTC

**Comment by paaljoachim** [comment] 2018-02-19 13:05
These are two different things.
#29 Is using translation to adjust strings where the login link is not mentioned.

#30 this is about on the main shop page clicking a simple product purchase button and not having the dependency message show up. I tried this again and noticed that for whatever reason it works now. The dependency message does show up.
So I will leave this closed.
