### ISSUE TITLE
Product Dependencies not being honored at checkout...

### ISSUE THREAD

**Issue by dlfdlf56** [somewherewarm/woocommerce-product-dependencies#12] opened 2017-06-20 03:41 UTC
I've tested this multiple times with different products and the result is always the same.  Product Dependencies works if you try to place an item in the cart without the dependency, but if you place both items in the cart and then remove the mandatory item it fails to recognize that the mandatory product is no longer in the cart and allows checkout without any errors.  Screenshots showing the issue are below...

Screenshot show the dependency working on attempt to add item to cart:
![image](https://user-images.githubusercontent.com/29309591/27315579-078c767c-5540-11e7-88b5-dd9194729f16.png)

screenshot showing product being allowed to be added to the cart after the mandatory product is added:
![image](https://user-images.githubusercontent.com/29309591/27315597-2201a720-5540-11e7-94a2-5711daba2873.png)

screenshot of the dependent product only in the cart:
![image](https://user-images.githubusercontent.com/29309591/27315635-4623ee4c-5540-11e7-9e5b-da5f5ad55e6f.png)

screenshot of advancing to checkout:
![image](https://user-images.githubusercontent.com/29309591/27315648-595230e6-5540-11e7-820a-f739a873d37d.png)

screenshot of successful checkout:
![image](https://user-images.githubusercontent.com/29309591/27315661-6a382dc0-5540-11e7-8154-5bed9ab2f25a.png)

**Comment by franticpsyx** [comment] 2017-06-20 09:02
Can you please share the following details:

- WC version
- WP version
- WC Product Dependencies version

Thanks!

**Comment by franticpsyx** [comment] 2017-06-20 09:05
Also it looks like that you have other plugins installed while testing. 

Very often issues like this may be caused by either a conflict with your theme or with another plugin. Please re-test after:

- temporarily **switching back to a default WordPress theme** (or Storefront); and 
- **disabling all other plugins except for WooCommerce (and Product Dependencies)**.

**Comment by dlfdlf56** [comment] 2017-06-20 14:41
WC version is 3.0.8
WP version is 4.8
WC Product Dependencies is 1.1.1

**Comment by franticpsyx** [comment] 2017-06-21 09:09
Hey @dlfdlf56 -- I am able to replicate an issue with Variable products :) Will push a fix in a bit.

**Comment by franticpsyx** [comment] 2017-06-21 09:41
Should be fixed in `master` - @dlfdlf56 can you please replace your current version with https://github.com/somewherewarm/woocommerce-product-dependencies/archive/master.zip (1.1.2-dev) and report back? Thanks!

**Comment by dlfdlf56** [comment] 2017-06-21 14:57
Its working perfectly!  Thanks!

**Closed** 2017-06-23 11:00 UTC
