### ISSUE TITLE
WC 2.6: Fatal error when 'Ownership' or 'Either' Dependency Type is selected

### ISSUE THREAD

**Issue by jimjasson** [somewherewarm/woocommerce-product-dependencies#21] opened 2017-12-28 09:52 UTC
To replicate this:

- Install WooCommerce v2.6 .

- In Product Dependencies select some products or categories.

- In the Dependency Type dropdown, select Ownership or Either.

- Click to view the product.

- Click 'Add to Cart'.

**Comment by franticpsyx** [comment] 2018-01-04 08:40
@jimjasson what's the Fatal Error content? Did you find the cause?

**Comment by franticpsyx** [comment] 2018-01-09 13:39
Closed via https://github.com/somewherewarm/woocommerce-product-dependencies/pull/24

Props to @jimjasson

**Closed by franticpsyx** 2018-01-09 13:39 UTC
Labels: bug:confirmed, priority:high
