### ISSUE TITLE
Dependencies Stopped Working

### ISSUE THREAD

**Issue by anitasmithers** [somewherewarm/woocommerce-product-dependencies#9] opened 2017-03-17 16:47 UTC
When I first set up my woocommerce site, I was able to use this Dependencies Plug-in perfectly and no one was able to purchase those products (books) unless they also purchased the workshops the books were dependent on. But a purchase just came thru for a book only (which should not have happened) and now, after testing, I find out that I can’t make the dependencies work at all. I haven’t changed anything. No new plug-ins or anything extra. It just stopped working.

http://www.APHAWorkshops.com  you should not be able to purchase any book without a purchase of a workshop. Here is a copy of how the dependencies are set up: http://aphaworkshops.com/images/dependencies.PNG 

Help please!

**Comment by franticpsyx** [comment] 2017-03-17 17:00
Hey @anitasmithers -- can you share:

- WooCommerce version
- WC Product Dependencies plugin version

Also are you using any non-core product types?

**Comment by franticpsyx** [comment] 2017-03-17 17:09
Should be fixed in latest update - v1.1.1

**Closed** 2017-03-17 17:08 UTC

**Comment by anitasmithers** [comment] 2017-03-17 17:16
Woo-commerce version:  2.6.14
Dependencies version:  1.1.0

**Comment by franticpsyx** [comment] 2017-03-17 17:17
Thanks! Can you please update to v1.1.1 and see if the issue is resolved?

**Comment by anitasmithers** [comment] 2017-03-17 17:18
My admin isn't identifying an update... what's the best way to update?

Hey - thanks for helping me so quickly!

**Comment by anitasmithers** [comment] 2017-03-17 17:23
Yes - it works now - thank you!  Thanks for helping me so quickly, too.
